# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Parel < Formula
  desc "Parel CLI - single binary for the Parel AI gateway"
  homepage "https://parel.cloud"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/parel-cloud/parel-cli/releases/download/v0.1.1/parel_0.1.1_darwin_amd64.tar.gz"
      sha256 "eabde1494022d4b7a424f0524ed48793a3a5f764ef6e403ef96c29c93f1440ae"

      define_method(:install) do
        bin.install "parel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/parel-cloud/parel-cli/releases/download/v0.1.1/parel_0.1.1_darwin_arm64.tar.gz"
      sha256 "fad07213518a22b519d309bdf9970c2df13b95d6cb47717b27c34407c0b29a2b"

      define_method(:install) do
        bin.install "parel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/parel-cloud/parel-cli/releases/download/v0.1.1/parel_0.1.1_linux_amd64.tar.gz"
      sha256 "1d5b4ca59562321c8265faf7124ae79ef462e643c39fee8ea7814df0a143530c"
      define_method(:install) do
        bin.install "parel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/parel-cloud/parel-cli/releases/download/v0.1.1/parel_0.1.1_linux_arm64.tar.gz"
      sha256 "e3d445b95f6de7b0a86dc47accf612bce942d2e98f128c42f1bbab527c1825cb"
      define_method(:install) do
        bin.install "parel"
      end
    end
  end

  def post_install
    # Apple Gatekeeper bypass for v0.1 unsigned builds. Will become a no-op
    # once we ship notarized binaries in v0.1.1+.
    system "/usr/bin/xattr", "-d", "com.apple.quarantine", "#{bin}/parel" rescue nil
  end

  test do
    system "#{bin}/parel", "version"
  end
end
