# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Parel < Formula
  desc "Parel CLI - single binary for the Parel AI gateway"
  homepage "https://parel.cloud"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/parel-cloud/parel-cli/releases/download/v0.1.0/parel_0.1.0_darwin_amd64.tar.gz"
      sha256 "f8c366e30363e33caa2258c8097e94f34389d2991627da4a2d0014582637c026"

      define_method(:install) do
        bin.install "parel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/parel-cloud/parel-cli/releases/download/v0.1.0/parel_0.1.0_darwin_arm64.tar.gz"
      sha256 "0fe7b83bf3c86af1e40966f6316b43c6b0e3d43d1ed98d69cc1151cd776bca8d"

      define_method(:install) do
        bin.install "parel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/parel-cloud/parel-cli/releases/download/v0.1.0/parel_0.1.0_linux_amd64.tar.gz"
      sha256 "4a35154d4c92850d0c7dfcaa7a083b91f3cbfea1111f72f3ce3e8bb5840f2b58"
      define_method(:install) do
        bin.install "parel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/parel-cloud/parel-cli/releases/download/v0.1.0/parel_0.1.0_linux_arm64.tar.gz"
      sha256 "b7bff316ea003e3d33c5d851c3cbc04a5930cd0f7701b4f15e838d29fbc90666"
      define_method(:install) do
        bin.install "parel"
      end
    end
  end

  def post_install
    # Apple Gatekeeper bypass for v0.1 unsigned builds. Will become a no-op
    # once we ship notarized binaries in v0.1.1+.
    system "/usr/bin/xattr", "-d", "com.apple.quarantine", "#{bin}/parel" rescue nil
  end

  test do
    system "#{bin}/parel", "version"
  end
end
