# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Parel < Formula
  desc "Parel CLI - single binary for the Parel AI gateway"
  homepage "https://parel.cloud"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/parel-cloud/parel-cli/releases/download/v0.1.5/parel_0.1.5_darwin_amd64.tar.gz"
      sha256 "ff501ae7ce02660c5feb8784e8c01d6f6a8b0a45b99b2a6deb9ab813f585394a"

      define_method(:install) do
        bin.install "parel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/parel-cloud/parel-cli/releases/download/v0.1.5/parel_0.1.5_darwin_arm64.tar.gz"
      sha256 "831c9144ab08630a78964fcf329fb1f99b5860380de7ed9bd5cfae592f8924cc"

      define_method(:install) do
        bin.install "parel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/parel-cloud/parel-cli/releases/download/v0.1.5/parel_0.1.5_linux_amd64.tar.gz"
      sha256 "589595c5764d224376dfd5822ea52438759a8b88daa65f8e9ab4396061e4bbc1"
      define_method(:install) do
        bin.install "parel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/parel-cloud/parel-cli/releases/download/v0.1.5/parel_0.1.5_linux_arm64.tar.gz"
      sha256 "2ce755379fc0a8b98156ba28bc665ccc5b985089ec6fbbb4f2f7566e6bde45ef"
      define_method(:install) do
        bin.install "parel"
      end
    end
  end

  def post_install
    # Apple Gatekeeper bypass for v0.1 unsigned builds. Will become a no-op
    # once we ship notarized binaries in v0.1.1+.
    system "/usr/bin/xattr", "-d", "com.apple.quarantine", "#{bin}/parel" rescue nil
  end

  test do
    system "#{bin}/parel", "version"
  end
end
